### ISSUE TITLE
Test are dependent on locale

### ISSUE THREAD

**Issue by pemensik** [NetworkManager/NetworkManager-ci#330]
I was retesting dnsmasq tests on my system, where LANG=cs_CZ.UTF-8 is configured. It makes some checks to fail, since it is checking output of nmcli, which might be translated. I think it should set explicitly default locale before running.

**Comment by pemensik** [comment]
environment:
      LC_ALL: C.UTF-8
in tests.yaml seems to fix the issue, at least on dnsmasq

**Comment by vbenes** [comment]
fixed by:
https://gitlab.freedesktop.org/NetworkManager/NetworkManager-ci/commit/f3d433683c1c1921632dc11bc51acd3d2a3428fb
